# nginx 与 app 开发环境下可选
# Windows 下 需保证挂载目录可访问
version: 3
services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: file-server-mysql
    restart: always
    environment:
      MYSQL_DATABASE: file_server
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: %
    ports:
      - 3306:3306
    volumes:
      - /data/file-server/mysql:/var/lib/mysql
  minio:
    image: minio/minio
    container_name: file-server-minio
    restart: always
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    command: server /data  --console-address ':9001'
  nginx:
    image: nginx:1.17.0
    container_name: file-server-nginx
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - minio
  app:
    image: file-server-java
    container_name: file-server-app
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /tmp/file-server/log:/app/log
    ports:
      - 9999:9999
    depends_on:
      - mysql