# 数据库配置
db:
  host: 192.168.41.4
  port: 3306
  name: file_server
  user: root
  password: muming996211478

# minio
minio:
  endpoint: http://192.168.41.4
  port: 9002
  user: minio_zKyQZQ
  password: minio_JJPmSA
  bucket: file-server-dev

# 业务
download:
  # java服务访问地址
  host: http://localhost:9090
  # 是否使用预签url
  presigned: true

# 日志
logging:
  level:
    com.xing: debug
